use structa_ast::*;
use structa_transformer::{TransformOptions, TransformedProgram, TransformedStmt, Transformer};
use thiserror::Error;

#[derive(Error, Debug)]
pub enum CodegenError {
    #[error("Codegen error: {0}")]
    Message(String),
}

pub type Result<T> = std::result::Result<T, CodegenError>;

pub struct CodeGenerator {
    options: CodegenOptions,
    indent: usize,
}

#[derive(Debug, Clone)]
pub struct CodegenOptions {
    pub target: String,
    pub module: String,
    pub strict: bool,
    pub emit_decorators: bool,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            target: "es2022".to_string(),
            module: "commonjs".to_string(),
            strict: true,
            emit_decorators: true,
        }
    }
}

impl CodeGenerator {
    pub fn new(options: CodegenOptions) -> Self {
        Self { options, indent: 0 }
    }

    pub fn generate(&mut self, program: Program) -> Result<String> {
        let mut transformer = Transformer::new(TransformOptions {
            target: self.options.target.clone(),
            module: self.options.module.clone(),
            strict_mode: self.options.strict,
            decorators_enabled: self.options.emit_decorators,
        });

        let transformed = transformer
            .transform(program)
            .map_err(|e| CodegenError::Message(e.to_string()))?;

        self.emit_program(transformed)
    }

    fn emit_program(&mut self, program: TransformedProgram) -> Result<String> {
        let mut output = String::new();

        output.push_str("// Auto-generated by Structa\n");
        output.push_str(&format!("// Target: {}\n", program.options.target));
        output.push_str(&format!("// Module: {}\n\n", program.options.module));

        output.push_str("import { Controller, Service, Guard, Middleware, Resolver, Gateway, Injectable } from '@structa/runtime';\n\n");

        for stmt in &program.statements {
            let stmt_output = self.emit_stmt(stmt)?;
            if !stmt_output.is_empty() {
                output.push_str(&stmt_output);
                output.push('\n');
            }
        }

        Ok(output)
    }

    fn emit_stmt(&mut self, stmt: &TransformedStmt) -> Result<String> {
        match stmt {
            TransformedStmt::Class {
                name,
                extends,
                implements,
                body,
                decorators,
            } => self.emit_class(name, extends.as_deref(), implements, body, decorators),
            TransformedStmt::Module {
                name,
                imports,
                exports,
                body,
            } => self.emit_module(name, imports, exports, body),
            TransformedStmt::Interface {
                name,
                extends,
                body,
                decorators,
            } => self.emit_interface(name, extends, body, decorators),
            TransformedStmt::Enum {
                name,
                members,
                is_const,
                decorators,
            } => self.emit_enum(name, members, is_const, decorators),
            TransformedStmt::TypeAlias {
                name,
                type_params,
                type_annotation,
                decorators,
            } => self.emit_type_alias(name, type_params, type_annotation, decorators),
            TransformedStmt::Import {
                path,
                names,
                is_default,
            } => self.emit_import(path, names, *is_default),
            TransformedStmt::Expr { expr_str } => Ok(format!("{};\n", expr_str)),
        }
    }

    fn emit_class(
        &self,
        name: &str,
        extends: Option<&str>,
        implements: &[String],
        body: &[String],
        decorators: &[Decorator],
    ) -> Result<String> {
        let mut output = String::new();

        for decorator in decorators {
            output.push_str(&format!("{}\n", self.emit_decorator(decorator)));
        }

        let extends_str = extends
            .map(|e| format!(" extends {}", e))
            .unwrap_or_default();
        let implements_str = if !implements.is_empty() {
            format!(" implements {}", implements.join(", "))
        } else {
            String::new()
        };

        output.push_str(&format!(
            "@Injectable()\nexport class {}{}{} {{\n",
            name, extends_str, implements_str
        ));

        for line in body {
            output.push_str(&format!("{}\n", line));
        }

        output.push_str("}\n");

        Ok(output)
    }

    fn emit_module(
        &self,
        name: &str,
        imports: &[structa_transformer::TransformedImport],
        exports: &[String],
        _body: &[TransformedStmt],
    ) -> Result<String> {
        let mut output = String::new();

        output.push_str(&format!("// Module: {}\n", name));

        for import in imports {
            let names_str = if import.names.is_empty() {
                "* as m".to_string()
            } else {
                import.names.join(", ")
            };
            output.push_str(&format!(
                "import {{{}}} from '{}';\n",
                names_str, import.path
            ));
        }

        if !exports.is_empty() {
            output.push_str(&format!("export {{{}}};\n", exports.join(", ")));
        }

        Ok(output)
    }

    fn emit_interface(
        &self,
        name: &str,
        extends: &[String],
        body: &[structa_transformer::TransformedField],
        decorators: &[Decorator],
    ) -> Result<String> {
        let mut output = String::new();

        for decorator in decorators {
            output.push_str(&format!("{}\n", self.emit_decorator(decorator)));
        }

        let extends_str = if !extends.is_empty() {
            format!(" extends {}", extends.join(", "))
        } else {
            String::new()
        };

        output.push_str(&format!("export interface {}{} {{\n", name, extends_str));

        for field in body {
            let decorators = self.emit_field_decorators(&field.decorators);
            output.push_str(&format!("{}{};\n", decorators, field.field_type_str));
        }

        output.push_str("}\n");

        Ok(output)
    }

    fn emit_enum(
        &self,
        name: &str,
        members: &[String],
        is_const: &bool,
        decorators: &[Decorator],
    ) -> Result<String> {
        let mut output = String::new();

        for decorator in decorators {
            output.push_str(&format!("{}\n", self.emit_decorator(decorator)));
        }

        let const_kw = if *is_const { "const " } else { "" };
        output.push_str(&format!("export {}enum {} {{\n", const_kw, name));

        for member in members {
            output.push_str(&format!("  {},\n", member));
        }

        output.push_str("}\n");

        Ok(output)
    }

    fn emit_type_alias(
        &self,
        name: &str,
        type_params: &[String],
        type_annotation: &TypeAnnotation,
        decorators: &[Decorator],
    ) -> Result<String> {
        let mut output = String::new();

        for decorator in decorators {
            output.push_str(&format!("{}\n", self.emit_decorator(decorator)));
        }

        let params_str = if !type_params.is_empty() {
            format!("<{}>", type_params.join(", "))
        } else {
            String::new()
        };

        let type_str = self.emit_type(type_annotation)?;
        output.push_str(&format!(
            "export type {}{} = {};\n",
            name, params_str, type_str
        ));

        Ok(output)
    }

    fn emit_import(&self, path: &str, names: &[String], is_default: bool) -> Result<String> {
        if names.is_empty() {
            return Ok(format!("import * as m from '{}';\n", path));
        }

        let import_str = if is_default {
            format!("import {} from '{}';\n", names[0], path)
        } else {
            format!("import {{{}}} from '{}';\n", names.join(", "), path)
        };

        Ok(import_str)
    }

    fn emit_type(&self, type_annotation: &TypeAnnotation) -> Result<String> {
        match &type_annotation.kind {
            TypeKind::String => Ok("string".to_string()),
            TypeKind::Number | TypeKind::Integer | TypeKind::Float => Ok("number".to_string()),
            TypeKind::Boolean => Ok("boolean".to_string()),
            TypeKind::Void => Ok("void".to_string()),
            TypeKind::Null => Ok("null".to_string()),
            TypeKind::Undefined => Ok("undefined".to_string()),
            TypeKind::Any | TypeKind::Unknown => Ok("any".to_string()),
            TypeKind::Never => Ok("never".to_string()),
            TypeKind::Object => Ok("object".to_string()),
            TypeKind::Array(inner) => {
                let inner_str = self.emit_type(inner)?;
                Ok(format!("{}[]", inner_str))
            }
            TypeKind::Optional(inner) => {
                let inner_str = self.emit_type(inner)?;
                Ok(format!("{} | null", inner_str))
            }
            TypeKind::Union(types) => {
                let type_strs: Result<Vec<String>> =
                    types.iter().map(|t| self.emit_type(t)).collect();
                Ok(type_strs?.join(" | "))
            }
            TypeKind::Identifier(name) => Ok(name.clone()),
            TypeKind::Generic { name, args } => {
                let args_str: Result<Vec<String>> =
                    args.iter().map(|a| self.emit_type(a)).collect();
                Ok(format!("{}<{}>", name, args_str?.join(", ")))
            }
            TypeKind::Fn {
                params,
                return_type,
            } => {
                let params_str: Result<Vec<String>> =
                    params.iter().map(|p| self.emit_type(p)).collect();
                let ret_str = self.emit_type(return_type)?;
                Ok(format!("({}) => {}", params_str?.join(", "), ret_str))
            }
        }
    }

    fn emit_decorator(&self, decorator: &Decorator) -> String {
        if decorator.args.is_empty() {
            format!("@{}", decorator.name)
        } else {
            let args_str = decorator
                .args
                .iter()
                .map(|a| self.emit_expr(a))
                .collect::<Vec<_>>()
                .join(", ");
            format!("@{}({})", decorator.name, args_str)
        }
    }

    fn emit_field_decorators(&self, decorators: &[Decorator]) -> String {
        if decorators.is_empty() {
            String::new()
        } else {
            let decs: Vec<String> = decorators.iter().map(|d| self.emit_decorator(d)).collect();
            format!("{}\n  ", decs.join("\n"))
        }
    }

    fn emit_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::String(s, _) => format!("\"{}\"", s),
            Expr::Number(n, _) => n.to_string(),
            Expr::Integer(n, _) => n.to_string(),
            Expr::Boolean(b, _) => b.to_string(),
            Expr::Identifier(s, _) => s.clone(),
            Expr::Null(_) => "null".to_string(),
            Expr::Undefined(_) => "undefined".to_string(),
            Expr::Binary {
                left, op, right, ..
            } => {
                let left_str = self.emit_expr(left);
                let right_str = self.emit_expr(right);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Subtract => "-",
                    BinaryOp::Multiply => "*",
                    BinaryOp::Divide => "/",
                    BinaryOp::Equals => "===",
                    BinaryOp::NotEquals => "!==",
                    BinaryOp::LessThan => "<",
                    BinaryOp::GreaterThan => ">",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    _ => "/* unknown op */",
                };
                format!("({} {} {})", left_str, op_str, right_str)
            }
            Expr::Call { callee, args, .. } => {
                let callee_str = self.emit_expr(callee);
                let args_str = args
                    .iter()
                    .map(|a| self.emit_expr(a))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}({})", callee_str, args_str)
            }
            _ => "/* unhandled expr */".to_string(),
        }
    }
}

pub fn generate_code(source: &str, options: CodegenOptions) -> Result<String> {
    use structa_parser::Parser;

    let mut parser = Parser::new(source);
    let program = parser
        .parse()
        .map_err(|e| CodegenError::Message(e.to_string()))?;

    let mut generator = CodeGenerator::new(options);
    generator.generate(program)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_generation() {
        let options = CodegenOptions::default();
        let generator = CodeGenerator::new(options);
        assert_eq!(generator.options.target, "es2022");
    }

    #[test]
    fn test_type_emission() {
        let options = CodegenOptions::default();
        let mut generator = CodeGenerator::new(options);

        let type_annotation = TypeAnnotation {
            kind: TypeKind::String,
            location: Location::default(),
        };

        let result = generator.emit_type(&type_annotation);
        assert!(result.is_ok());
        assert_eq!(result.unwrap(), "string");
    }

    #[test]
    fn test_simple_dsl_parsing() {
        let source = "service UserService {}";
        let result = generate_code(source, CodegenOptions::default());
        assert!(result.is_ok());
        let output = result.unwrap();
        assert!(output.contains("UserService"));
        assert!(output.contains("@Injectable"));
    }
}
