use anyhow::Result;
use std::path::PathBuf;
use tracing::info;

pub async fn run(schema: Option<PathBuf>, output: PathBuf, watch: bool) -> Result<()> {
    info!("Generating code from schema");
    
    let schema_path = schema.unwrap_or_else(|| PathBuf::from("schema.yaml"));
    
    if !schema_path.exists() {
        anyhow::bail!("Schema file not found: {:?}", schema_path);
    }
    
    info!("Schema: {:?}", schema_path);
    info!("Output: {:?}", output);
    
    std::fs::create_dir_all(&output)?;
    
    let content = std::fs::read_to_string(&schema_path)?;
    
    info!("Parsed schema, generating TypeScript types...");
    
    let types_file = output.join("types.generated.ts");
    std::fs::write(&types_file, generate_types(&content))?;
    
    info!("Generated: {:?}", types_file);
    println!("\n✅ Generated {} file(s)", 1);
    
    if watch {
        info!("Watch mode enabled");
    }
    
    Ok(())
}

fn generate_types(schema: &str) -> String {
    format!(r#"// This file is auto-generated by Structa
// DO NOT EDIT MANUALLY

export interface GeneratedTypes {{
    // TODO: Parse schema and generate types
}}

/**
 * Generated from schema:
 * {}
 */
export const schemaContent = `{}` as const;
"#, schema, schema)
}
