use crate::ast::{AstNode, Program};

pub fn compile(prog: &Program) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Structa v");
    out.push_str(env!("CARGO_PKG_VERSION"));
    out.push_str("\n\n");
    out.push_str("import { server } from '../runtime.js';\n\n");

    let mut route_declarations = Vec::new();
    for node in &prog.nodes {
        let (class_code, routes) = compile_node(node);
        out.push_str(&class_code);
        route_declarations.extend(routes);
    }

    if !route_declarations.is_empty() {
        out.push_str("\n// Routes\n");
        for route in route_declarations {
            out.push_str(&route);
            out.push('\n');
        }
    }

    out.push_str("\nserver.listen();\n");
    out
}

fn compile_node(node: &AstNode) -> (String, Vec<String>) {
    match node.kind.as_str() {
        "controller" => compile_controller(node),
        "service" => compile_service(node),
        "dto" => (compile_dto(node), Vec::new()),
        "repository" => (compile_repository(node), Vec::new()),
        "resolver" => compile_resolver(node),
        "middleware" => (compile_middleware(node), Vec::new()),
        "module" => (compile_module(node), Vec::new()),
        _ => (String::new(), Vec::new()),
    }
}

fn compile_controller(node: &AstNode) -> (String, Vec<String>) {
    let name = node.name.as_deref().unwrap_or("Controller");
    let mut out = format!("export class {} {{\n", name);
    let mut routes = Vec::new();
    let mut base_path = "/".to_string();
    let mut pending_decorators: Vec<(String, String)> = Vec::new();
    let mut injects: Vec<(String, String)> = Vec::new();

    let mut i = 0;
    while i < node.body.len() {
        let item = &node.body[i];
        match item.kind.as_str() {
            "_inject" => {
                let service_type = item
                    .props
                    .get("path")
                    .map(|s| s.as_str())
                    .unwrap_or("")
                    .to_string();
                if let Some(next_item) = node.body.get(i + 1) {
                    if next_item.kind.as_str() == "property" || next_item.kind.as_str() == "field" {
                        if let Some(prop_name) = &next_item.name {
                            injects.push((prop_name.clone(), service_type));
                            i += 1;
                        }
                    }
                }
            }
            "property" => {
                if item.name.as_deref() == Some("path") {
                    if let Some(v) = item.props.get("value") {
                        base_path = v.clone();
                    }
                } else if let Some(prop_name) = &item.name {
                    if let Some(value) = item.props.get("value") {
                        if !value.is_empty() {
                            out.push_str(&format!("    {} = {};\n", prop_name, value));
                        }
                    }
                }
            }
            "decorator" => {
                if let Some(method) = &item.name {
                    let path = item.props.get("path").map(|s| s.as_str()).unwrap_or("/");
                    pending_decorators.push((method.clone(), path.to_string()));
                }
            }
            "method" => {
                if let Some(method_name) = &item.name {
                    let params = item
                        .props
                        .get("params")
                        .map(|s| s.as_str())
                        .unwrap_or("req, res");
                    let body = item.props.get("body").map(|s| s.as_str()).unwrap_or("");
                    out.push_str(&format!(
                        "    async {}({}) {{\n        {}\n    }}\n",
                        method_name, params, body
                    ));

                    for (http_method, path) in pending_decorators.drain(..) {
                        let full_path = format!("{}{}", base_path.trim_end_matches('/'), path);
                        routes.push(format!(
                            "server.route({{ method: '{}', path: '{}', handler: async (req, res) => {{ const ctrl = new {}(); return await ctrl.{}(req, res); }} }});",
                            http_method, full_path, name, method_name
                        ));
                    }
                }
            }
            _ => {}
        }
        i += 1;
    }

    if !injects.is_empty() {
        out.push_str("\n    constructor() {\n");
        for (prop, service) in &injects {
            out.push_str(&format!(
                "        this.{} = Container.get('{}');\n",
                prop, service
            ));
        }
        out.push_str("    }\n");
    }

    out.push_str("}\n");
    (out, routes)
}

fn compile_service(node: &AstNode) -> (String, Vec<String>) {
    let name = node.name.as_deref().unwrap_or("Service");
    let mut out = format!("export class {} {{\n", name);
    let mut injects: Vec<(String, String)> = Vec::new();

    let mut i = 0;
    while i < node.body.len() {
        let item = &node.body[i];
        match item.kind.as_str() {
            "_inject" => {
                let service_type = item
                    .props
                    .get("path")
                    .map(|s| s.as_str())
                    .unwrap_or("")
                    .to_string();
                if let Some(next_item) = node.body.get(i + 1) {
                    if next_item.kind.as_str() == "property" || next_item.kind.as_str() == "field" {
                        if let Some(prop_name) = &next_item.name {
                            injects.push((prop_name.clone(), service_type));
                            i += 1;
                        }
                    }
                }
            }
            "property" => {
                if let Some(prop_name) = &item.name {
                    if let Some(value) = item.props.get("value") {
                        if !value.is_empty() {
                            out.push_str(&format!("    {} = {};\n", prop_name, value));
                        }
                    }
                }
            }
            "method" => {
                if let Some(method_name) = &item.name {
                    let params = item.props.get("params").map(|s| s.as_str()).unwrap_or("");
                    let body = item.props.get("body").map(|s| s.as_str()).unwrap_or("");
                    out.push_str(&format!(
                        "    async {}({}) {{\n        {}\n    }}\n",
                        method_name, params, body
                    ));
                }
            }
            _ => {}
        }
        i += 1;
    }

    if !injects.is_empty() {
        out.push_str("\n    constructor() {\n");
        for (prop, service) in &injects {
            out.push_str(&format!(
                "        this.{} = Container.get('{}');\n",
                prop, service
            ));
        }
        out.push_str("    }\n");
    }

    out.push_str("}\n");
    (out, Vec::new())
}

fn compile_dto(node: &AstNode) -> String {
    let name = node.name.as_deref().unwrap_or("Dto");
    let mut out = format!("export class {} {{\n", name);
    out.push_str("    constructor(data) {\n");

    for item in &node.body {
        if item.kind.as_str() == "field" {
            if let Some(field_name) = &item.name {
                out.push_str(&format!(
                    "        this.{} = data.{};\n",
                    field_name, field_name
                ));
            }
        }
    }

    out.push_str("    }\n}\n");
    out
}

fn compile_repository(node: &AstNode) -> String {
    let name = node.name.as_deref().unwrap_or("Repository");
    let mut out = format!("export class {} {{\n", name);

    for item in &node.body {
        if item.kind.as_str() == "method" {
            if let Some(method_name) = &item.name {
                let params = item.props.get("params").map(|s| s.as_str()).unwrap_or("");
                let body = item.props.get("body").map(|s| s.as_str()).unwrap_or("");
                out.push_str(&format!(
                    "    async {}({}) {{\n        {}\n    }}\n",
                    method_name, params, body
                ));
            }
        }
    }

    out.push_str("}\n");
    out
}

fn compile_resolver(node: &AstNode) -> (String, Vec<String>) {
    let name = node.name.as_deref().unwrap_or("Resolver");
    let mut out = format!("export class {} {{\n", name);
    let mut routes = Vec::new();
    let mut pending_decorators: Vec<(String, String)> = Vec::new();

    let mut i = 0;
    while i < node.body.len() {
        let item = &node.body[i];
        match item.kind.as_str() {
            "method" => {
                if let Some(method_name) = &item.name {
                    let params = item.props.get("params").map(|s| s.as_str()).unwrap_or("");
                    let body = item.props.get("body").map(|s| s.as_str()).unwrap_or("");
                    out.push_str(&format!(
                        "    {}({}) {{\n        {};\n    }}\n",
                        method_name, params, body
                    ));

                    for (http_method, path) in pending_decorators.drain(..) {
                        routes.push(format!(
                            "server.route({{ method: '{}', path: '{}', handler: (req, res) => new {}().{}(req, res) }});",
                            http_method, path, name, method_name
                        ));
                    }
                }
            }
            "decorator" => {
                if let Some(method) = &item.name {
                    let path = item.props.get("path").map(|s| s.as_str()).unwrap_or("/");
                    pending_decorators.push((method.clone(), path.to_string()));
                }
            }
            _ => {}
        }
        i += 1;
    }

    out.push_str("}\n");
    (out, routes)
}

fn compile_middleware(node: &AstNode) -> String {
    let name = node.name.as_deref().unwrap_or("Middleware");
    let mut out = format!("export class {} {{\n", name);

    for item in &node.body {
        if item.kind.as_str() == "method" {
            if let Some(method_name) = &item.name {
                let params = item
                    .props
                    .get("params")
                    .map(|s| s.as_str())
                    .unwrap_or("req, res");
                let body = item.props.get("body").map(|s| s.as_str()).unwrap_or("");
                let body_with_semicolons = body.replace(") ", "); ").replace("} ", "}; ");
                out.push_str(&format!(
                    "    {}({}) {{\n        {};\n    }}\n",
                    method_name, params, body_with_semicolons
                ));
            }
        }
    }

    out.push_str("    handle(req, res, next) {\n");
    out.push_str("        next();\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out.push_str(&format!("server.use(new {}());\n", name));
    out
}

fn compile_module(node: &AstNode) -> String {
    let name = node.name.as_deref().unwrap_or("Module");
    let mut out = format!("export class {} {{\n", name);

    for item in &node.body {
        if item.kind.as_str() == "property" {
            if let Some(prop_name) = &item.name {
                if let Some(value) = item.props.get("value") {
                    if !value.is_empty() {
                        out.push_str(&format!("    {} = {};\n", prop_name, value));
                    }
                }
            }
        } else if item.kind.as_str() == "method" {
            if let Some(method_name) = &item.name {
                let params = item.props.get("params").map(|s| s.as_str()).unwrap_or("");
                let body = item.props.get("body").map(|s| s.as_str()).unwrap_or("");
                out.push_str(&format!(
                    "    {}({}) {{\n        {}\n    }}\n",
                    method_name, params, body
                ));
            }
        }
    }

    out.push_str("}\n");
    out
}
